kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: dbt-docs
  namespace: nada
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50M
  labels:
    team: nada
spec:
  image: "{{ image }}"
  port: 8080
  ingresses:
    - "https://dbt.intern.dev.nav.no"
    - "https://dbt.ansatt.dev.nav.no"
  env:
    - name: DBT_DOCS_BUCKET
      value: nada-dbt-docs-dev
    - name: BIGQUERY_DATASET
      value: dbt_docs
    - name: BIGQUERY_TABLE
      value: views
  gcp:
    buckets:
      - name: nada-dbt-docs-dev
        publicAccessPrevention: true
        uniformBucketLevelAccess: true
    bigQueryDatasets:
      - cascadingDelete: false
        description: Metrikker på visninger av dbt dokumentasjon
        name: dbt_docs
        permission: READWRITE
